// Generated by CoffeeScript 1.3.3
(function() {

  window.App = angular.module('angular_tree_basic', ['$angularTree.directives']);

  window.App.controller('AppController', function($scope) {
    $scope.logs = [];
    $scope.treeOptions = {
      getChildren: function(node, cb) {
        return cb([
          {
            label: 'hello'
          }, {
            label: 'hi'
          }
        ]);
      },
      onLabelClick: function(node) {
        return $scope.logs = [
          {
            text: 'selected: ' + JSON.stringify({
              label: node.label,
              level: node.level
            })
          }
        ].concat($scope.logs);
      },
      onExpanderClick: function(node) {
        return $scope.logs = [
          {
            text: (node.expanded ? 'expanded' : 'collapsed') + ': ' + JSON.stringify({
              label: node.label,
              level: node.level
            })
          }
        ].concat($scope.logs);
      }
    };
    return $scope.treeRootNodes = [
      {
        label: 'hello'
      }, {
        label: 'hi'
      }
    ];
  });

}).call(this);
